services:
  momentum.client:
    container_name: momentum.client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: "always"
    depends_on:
      - momentum.backend
  momentum.backend:
    container_name: momentum.backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - momentum.database
    develop:
      watch:
        - action: rebuild
          path: ./*
  momentum.database:
    image: postgres:latest
    container_name: momentum.database
    environment:
      - POSTGRES_DB=momentum
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/momentum-db:/var/lib/postgresql/data
    ports: 
      - 5433:5432